version: '3.8'

services:
  scgm_rabbitmq:
    image: rabbitmq:3.12-management
    container_name: scgm_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - scgm-net

  scgm_mongo_db:
    image: mongo:7.0
    container_name: scgm_mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: scgm_routes_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - scgm-net

  scgm_postgresql_db:
    image: postgres:16
    container_name: scgm_postgresql_db
    environment:
      POSTGRES_USER: uwm_user
      POSTGRES_PASSWORD: uwm_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_postgresql_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - scgm-net

volumes:
  rabbitmq_data:
  mongodb_data:
  postgres_data:

networks:
  scgm-net:
    driver: bridge
