## Instance port
server:
  port: ${PORT:8081}

## Configuration for Eureka
eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}

## Configuration for App name and Spring Data
spring:
  application:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@
  datasource:
    url: jdbc:postgresql://localhost:5432/scgm_auth_db
    username: ${POSTGRES_USER:uwm_user}
    password: ${POSTGRES_PASSWORD:uwm_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:flyway_migration
  rabbitmq:
    host: ${RMQ_HOSTNAME:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USER:admin}
    password: ${RMQ_PASS:admin123}

jwt:
  secret: ${JWT_SECRET:dGhpc2lzYXZlcnlzZWNyZXRrZXlmb3J1d21hdXRoZW50aWNhdGlvbnNlcnZpY2U=}
  access-token-expiration: 1800000  # 15 minutes
  refresh-token-expiration: 604800000  # 7 days
