## Instance port
server:
  port: ${PORT:8180}

## Configuration for Eureka
eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}

## Configuration for App name and Spring Data
spring:
  application:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:admin123@localhost:27017/scgm_routes_db?authSource=admin}
      auto-index-creation: true
      database: scgm_routes_db

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    java:
      enabled: true
    git:
      enabled: true
      mode: simple
    build:
      enabled: true

## Url configs
scgm.containers.api.url: ${CONTAINERS_API_URL:http://localhost:8181}